"""Update datetime fields

Revision ID: 12ecbe3802d8
Revises: 12ffe622dee9
Create Date: 2024-07-09 13:03:24.097817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ecbe3802d8'
down_revision = '12ffe622dee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
